library(tidyverse)

# Forma convencional de hacer loops

for (i in c(1:10)){
     print (i^2)
     }

# Forma Tidy

## Para casos en los que el loop tiene una función con un input (y parámetros adicionales)

### Opción 1: formalizar la función
cuadrado <- function(valor1) {
     valor1^2
 }

map_dbl(.x = c(1:10), .f = cuadrado) # map_dbl devuelve lo mismo que map pero en forma de vector.

### Opción 2: función implícita
map_dbl(.x = c(1:10), .f = function(x) x^2)

### Opción 3: función gamma, ni siquiera declarando funciones
map_dbl(.x = c(1:10),.f = ~.x^2) 

## Para casos en los que el loop tiene una función con dos inputs (y parámetros adicionales)
map2_dbl(.x = c(1:10),.y = c(11:20),.f =  function(x,y) x*y)

### Opción 1: formalizar la función
producto <- function(valor1, valor2) {
     valor1*valor2
 }

map2_dbl(.x = c(1:10), .y = c(11:20), .f = producto) # map_dbl devuelve lo mismo que map pero en forma de vector.

### Opción 2: función implícita
map2_dbl(.x = c(1:10),.y = c(11:20),.f =  function(x,y) x*y)

### Opción 3: función gamma, ni siquiera declarando funciones
map2_dbl(.x = c(1:10),.y = c(11:20),.f = ~.x*.y)

_map y map2 iteran en paralelo sobre dos listas, por lo que no valen para casos en los que, por ejemplo, se quiera el producto de cacda elemento en c(1:10) por cada elemento en c(11:20), una lista de 100 resultados en vez de 10. Para ese caso hay que usar cross2 de la librería purrr._
